### ISSUE TITLE
Proposal: Use pre_output_filter instead of atbegshi

### ISSUE THREAD

**Issue by hmenke** [pgundlach/lvdebug#6]
I would like to propose using the `pre_output_filter` callback instead of the `atbegshi.sty`.  The advantage is that dependencies are reduced (one could even eliminate the `ifluatex` dependency with little effort).  The disadvantage is that this callback only iterates the document body without headers and footers.  I have not yet found a way to access the complete vertical list from Lua.

The implementation is located in my [callback](https://github.com/hmenke/lvdebug/tree/callback) branch.  I also took the freedom to restructure the nested `if-then-else` tree into a simple table lookup.

Below I show the output of the samples with my code.

### `sample.tex`

![sample](https://user-images.githubusercontent.com/1903556/39466998-de436f3a-4d7f-11e8-9fb1-3ff54b26b639.png)

### `sample-plain.tex`

![sample-plain](https://user-images.githubusercontent.com/1903556/39467003-e7197208-4d7f-11e8-807b-5dc5b5a59ee5.png)

**Comment by pgundlach** [comment]
First question: is the `atbegshi` dependency bad in any way? I don't know much about it.

**Comment by hmenke** [comment]
At least in Plain TeX the `atbegshi` package improperly loads `ifpdf` which leads to spurious characters appearing in the output.
![test](https://user-images.githubusercontent.com/1903556/39469449-5dd01a12-4d8c-11e8-9871-62df35555fde.png)

**Comment by hmenke** [comment]
Still looking for the right callback.  Continued here: https://tug.org/pipermail/luatex/2018-May/006814.html
